# coding: utf-8

"""
    NI Project Anomaly Detection Module

    NI VNF Anomaly Detection Module for the NI Project.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.ad_info import AdInfo  # noqa: E501
from openapi_client.rest import ApiException

class TestAdInfo(unittest.TestCase):
    """AdInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AdInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdInfo`
        """
        model = openapi_client.models.ad_info.AdInfo()  # noqa: E501
        if include_optional :
            return AdInfo(
                vnf_prefix = ''
            )
        else :
            return AdInfo(
        )
        """

    def testAdInfo(self):
        """Test AdInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
