# coding: utf-8

"""
    NI Project Anomaly Detection Module

    NI VNF Anomaly Detection Module for the NI Project.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import openapi_client
from openapi_client.api.vnf_anomaly_detection_api import VNFAnomalyDetectionApi  # noqa: E501
from openapi_client.rest import ApiException


class TestVNFAnomalyDetectionApi(unittest.TestCase):
    """VNFAnomalyDetectionApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.vnf_anomaly_detection_api.VNFAnomalyDetectionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_sla_detection_result(self):
        """Test case for get_sla_detection_result

        Get VNF Anomaly Detection Model's Prediction Results - SLA Violations  # noqa: E501
        """
        pass

    def test_get_vnf_info(self):
        """Test case for get_vnf_info

        Get VNFs' basic information that configure SFC  # noqa: E501
        """
        pass

    def test_get_vnf_resource_usage(self):
        """Test case for get_vnf_resource_usage

        Get VNFs' Resource Usages in Real-Time  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
