# coding: utf-8

"""
    NI Project Anomaly Detection Module

    NI VNF Anomaly Detection Module for the NI Project.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.vnf_instance import VNFInstance  # noqa: E501
from openapi_client.rest import ApiException

class TestVNFInstance(unittest.TestCase):
    """VNFInstance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test VNFInstance
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VNFInstance`
        """
        model = openapi_client.models.vnf_instance.VNFInstance()  # noqa: E501
        if include_optional :
            return VNFInstance(
                id = '', 
                name = '', 
                status = '', 
                flavor_id = '', 
                node_id = '', 
                ports = [
                    {port_name=port_name, network_id=network_id, ip_addresses=[ip_addresses, ip_addresses], port_id=port_id}
                    ]
            )
        else :
            return VNFInstance(
        )
        """

    def testVNFInstance(self):
        """Test VNFInstance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
